-- Story 3.4 (ADR-0011): supports GET /v1/posts' cursor-based pagination.
--
-- Ordering by `seq` (a monotonic identity column), not `created_at`: a
-- TIMESTAMPTZ column has microsecond precision in Postgres, but pg's client
-- returns it as a JS Date (millisecond precision only) — rows inserted within
-- the same millisecond would round-trip through a cursor with their true
-- ordering lost, producing genuine duplicates across pages. A monotonic
-- integer sequence has no such precision-loss class of bug. See
-- .claude/skills/posts-api/SKILL.md.
ALTER TABLE social_posts ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_social_posts_tenant_seq
  ON social_posts (tenant_id, seq);
