-- Story 3.5 (ADR-0018): partition social_posts monthly by created_at — not
-- published_at, which ADR-0018's implementation default literally names.
-- published_at is nullable (Story 4.2 — only enriched posts have it), and
-- Postgres requires a partitioned table's partition key to be part of its
-- primary key, which must be NOT NULL. Retention is conceptually about
-- hot-storage age since *ingestion*, not the source platform's original
-- publish date, so created_at (always NOT NULL DEFAULT now()) is both the
-- technically necessary and the more conceptually correct choice — logged
-- as a dated Amendment Log entry on ADR-0018, not decided silently. See
-- .claude/skills/data-retention-and-archival/SKILL.md.
--
-- acquisition_started_at is a new, denormalized copy of the referenced
-- IngestionRun's started_at, populated by insertSocialPost() alongside
-- acquisition_id (Story 3.5, ADR-0018). Originally added specifically to
-- back a composite foreign key (acquisition_id, acquisition_started_at) ->
-- ingestion_runs(id, started_at) once ingestion_runs became partitioned
-- (migration 0011, which invalidated the old plain acquisition_id -> id
-- FK). That composite FK is deliberately NOT created here: Postgres
-- refuses ALTER TABLE ... DETACH PARTITION on ingestion_runs while any row
-- elsewhere still holds a live FK into it, which makes a real, enforced FK
-- fundamentally incompatible with ingestion_runs' own whole-row archival
-- (ingestionRunArchival.ts genuinely drops aged-out partitions — see that
-- file). Discovered empirically while building this story, not assumed —
-- confirmed with the user before dropping the constraint. The "every post
-- traces to a real run" guarantee is application-enforced only from here
-- (insertSocialPost() always populates both columns correctly), the same
-- tier author_id already partly relies on. See
-- .claude/skills/data-retention-and-archival/SKILL.md and
-- .claude/skills/social-post-lineage/SKILL.md.
--
-- Rebuilt via backup-table-then-recreate, same reasoning as migration 0011.
CREATE TABLE social_posts_data_backup AS SELECT * FROM social_posts;

DROP TABLE social_posts;

CREATE TABLE social_posts (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  raw_payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  author_id UUID REFERENCES authors(id),
  post_geo_location JSONB,
  acquisition_id UUID,
  acquisition_started_at TIMESTAMPTZ,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  published_at TIMESTAMPTZ,
  enrichment JSONB,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE social_posts_default PARTITION OF social_posts DEFAULT;

DO $$
DECLARE
  month_start date;
  month_end date;
  partition_name text;
BEGIN
  FOR i IN -24..3 LOOP
    month_start := date_trunc('month', CURRENT_DATE) + (i || ' months')::interval;
    month_end := month_start + interval '1 month';
    partition_name := 'social_posts_y' || to_char(month_start, 'YYYY') || 'm' || to_char(month_start, 'MM');
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF social_posts FOR VALUES FROM (%L) TO (%L)',
      partition_name, month_start, month_end
    );
  END LOOP;
END
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON social_posts TO app_user;

ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_posts FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON social_posts
  FOR ALL
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

CREATE INDEX idx_social_posts_tenant_seq ON social_posts (tenant_id, seq);

INSERT INTO social_posts (id, tenant_id, raw_payload, created_at, author_id, post_geo_location, acquisition_id, acquisition_started_at, seq, published_at, enrichment)
SELECT b.id, b.tenant_id, b.raw_payload, b.created_at, b.author_id, b.post_geo_location, b.acquisition_id,
       ir.started_at, b.seq, b.published_at, b.enrichment
FROM social_posts_data_backup b
LEFT JOIN ingestion_runs ir ON ir.id = b.acquisition_id;

-- seq is GENERATED BY DEFAULT, so the explicit values copied above don't
-- automatically advance its identity sequence — bump it past the highest
-- copied value so future inserts never collide.
SELECT setval(pg_get_serial_sequence('social_posts', 'seq'), COALESCE((SELECT MAX(seq) FROM social_posts), 1));

DROP TABLE social_posts_data_backup;

-- Idempotent helper for creating a specific month's partition on demand.
CREATE OR REPLACE FUNCTION ensure_social_posts_partition(target_month date) RETURNS void AS $$
DECLARE
  month_start date := date_trunc('month', target_month);
  month_end date := month_start + interval '1 month';
  partition_name text := 'social_posts_y' || to_char(month_start, 'YYYY') || 'm' || to_char(month_start, 'MM');
BEGIN
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS %I PARTITION OF social_posts FOR VALUES FROM (%L) TO (%L)',
    partition_name, month_start, month_end
  );
END;
$$ LANGUAGE plpgsql;
